# Dataset 살펴보기
> 그냥 head, tail 정도만 찍어보자.<br>
사실 숫자로 구성된 데이터셋들은 kaggle 필사할 때 보면 중앙값, 최소 최대 표준편차 등 혹은 feature engineering(feature 여러개를 합쳐 하나의 값으로 만들고 그 feature를 살펴보기)등을 통해서 다양하게 살펴보곤 하던데, 텍스트 형식일 경우 어떤 방식으로 살펴봐야 하는지조차 감이 안온다. 분포를 시각화 하는 정도..? 시각화는 내일해보자.

In [2]:
import pandas as pd
import os

print("done")

done

In [13]:
data_cscall_path = os.path.join("./datasets/cscall/Training/shop", "AS_Training.json")

df_cscall = pd.read_json(data_path, encoding='ms949')

In [15]:
df_cscall.head()

,도메인,카테고리,대화셋일련번호,화자,문장번호,고객의도,상담사의도,QA,고객질문(요청),상담사질문(요청),고객답변,상담사답변,개체명,용어사전,지식베이스
0,K쇼핑,AS,S5513,상담사,1,,,A,,,,저는 ㅇㅇㅇ입니다.,ㅇㅇㅇ,,ㅇㅇㅇ/상담사명
1,K쇼핑,AS,S5513,고객,2,구매상품확인,,Q,네. 아쿠아 청소기를 샀었는데요.,,,,아쿠아 청소기,,아쿠아 청소기/상품명
2,K쇼핑,AS,S5513,상담사,3,,고객의도파악및구매상품확인,Q,,아. 그러십니까?,,,,,
3,K쇼핑,AS,S5513,고객,4,상담이력확인,,Q,네. 얼마 전에도 전화 한 번 드렸던 적이 있어요.,,,,"전화, 한 번",,한 번/횟수
4,K쇼핑,AS,S5513,상담사,5,,,A,,,,아. 네.,,,

In [16]:
df_cscall.tail()

,도메인,카테고리,대화셋일련번호,화자,문장번호,고객의도,상담사의도,QA,고객질문(요청),상담사질문(요청),고객답변,상담사답변,개체명,용어사전,지식베이스
13928,K쇼핑,AS,S1402,고객,32,,,A,,,네 그래주세요\r\n,,,,
13929,K쇼핑,AS,S1402,상담사,33,,고객의사확인,Q,,더 문의할 사항 없습니까? \r\n,,,"사항, 문의",,
13930,K쇼핑,AS,S1402,고객,34,,,A,,,예 없습니다 \r\n,,,,
13931,K쇼핑,AS,S1402,상담사,35,,,A,,,,행복을 전하는 OOO이었습니다 \r\n안 되면 하루 이틀 안에 연락 주시기 바랍니다...,"행복, ㅇㅇㅇ, 하루, 이틀, 연락",,"ㅇㅇㅇ/상담사명, 하루/기간, 이틀/기간"
13932,K쇼핑,AS,S1402,고객,36,,,A,,,네 알겠습니다 \r\n,,,,

In [21]:
df_cscall.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13933 entries, 0 to 13932
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   도메인        13933 non-null  object
 1   카테고리       13933 non-null  object
 2   대화셋일련번호    13933 non-null  object
 3   화자         13933 non-null  object
 4   문장번호       13933 non-null  int64
 5   고객의도       13933 non-null  object
 6   상담사의도      13933 non-null  object
 7   QA         13933 non-null  object
 8   고객질문(요청)   13933 non-null  object
 9   상담사질문(요청)  13933 non-null  object
 10  고객답변       13933 non-null  object
 11  상담사답변      13933 non-null  object
 12  개체명        13933 non-null  object
 13  용어사전       13933 non-null  object
 14  지식베이스      13933 non-null  object
dtypes: int64(1), object(14)
memory usage: 1.6+ MB

In [24]:
df_cscall.describe()

               문장번호
count  13933.000000
mean      16.762363
std       13.129504
min        1.000000
25%        7.000000
50%       14.000000
75%       23.000000
max      124.000000

In [56]:
data_dktc_path = os.path.join("./datasets/dktc/data", "train.csv")

df_dktc = pd.read_csv(data_dktc_path, encoding='utf-8')

In [57]:
df_dktc.head()

   idx      class                                       conversation
0    0      협박 대화  지금 너 스스로를 죽여달라고 애원하는 것인가?\n 아닙니다. 죄송합니다.\n 죽을 ...
1    1      협박 대화  길동경찰서입니다.\n9시 40분 마트에 폭발물을 설치할거다.\n네?\n똑바로 들어 ...
2    2  기타 괴롭힘 대화  너 되게 귀여운거 알지? 나보다 작은 남자는 첨봤어.\n그만해. 니들 놀리는거 재미...
3    3      갈취 대화  어이 거기\n예??\n너 말이야 너. 이리 오라고\n무슨 일.\n너 옷 좋아보인다?...
4    4      갈취 대화  저기요 혹시 날이 너무 뜨겁잖아요? 저희 회사에서 이 선크림 파는데 한 번 손등에 ...

In [58]:
df_dktc.tail()

       idx        class                                       conversation
3945  3945    기타 괴롭힘 대화  준하야 넌 대가리가 왜이렇게 크냐?\n내 머리가 뭐.\n밥먹으면 대가리만 크냐 너는...
3946  3946        갈취 대화  내가 지금 너 아들 김길준 데리고 있어. 살리고 싶으면 계좌에 1억만 보내\n예.?...
3947  3947  직장 내 괴롭힘 대화  나는 씨 같은 사람 보면 참 신기하더라. 어떻게 저렇게 살지.\n왜 그래. 들리겠어...
3948  3948        갈취 대화  누구맘대로 여기서 장사하래?\n이게 무슨일입니까?\n남의 구역에서 장사하려면 자릿세...
3949  3949  직장 내 괴롭힘 대화  희정씨\n네?\n주말에 시간이 넘쳐나나봐\n갑자기 왜그러세요?\n손이 빤짝빤짝 네일...

In [59]:
df_dktc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3950 entries, 0 to 3949
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   idx           3950 non-null   int64
 1   class         3950 non-null   object
 2   conversation  3950 non-null   object
dtypes: int64(1), object(2)
memory usage: 92.7+ KB

In [64]:
data_feeling_path = os.path.join("./datasets/feeling/Training", "final_Training.xlsx")

df_feeling = pd.read_excel(data_feeling_path)

In [65]:
df_feeling.head()

,번호,연령,성별,상황키워드,신체질환,감정_대분류,감정_소분류,사람문장1,시스템응답1,사람문장2,시스템응답2,사람문장3,시스템응답3,사람문장4,시스템응답4
0,44164,청년,남성,"연애, 결혼, 출산",해당없음,기쁨,신이 난,아내가 드디어 출산하게 되어서 정말 신이 나.,아내분이 출산을 하시는군요. 정말 축하드려요.,아 지금 정말 신이 나.,잘 된 일이네요.,아기가 점점 클게 벌써 기대가 되네. 내가 많이 놀아줘야지.,좋은 아빠가 되실 거 같아요. 진심으로 축하드려요.,NaN,NaN
1,3926,노년,남성,"건강, 죽음",만성질환 유,불안,스트레스 받는,당뇨랑 합병증 때문에 먹어야 할 약이 열 가지가 넘어가니까 스트레스야.,약 종류가 많아 번거로우시겠어요.,건강할 때 관리 좀 잘할걸 하는 생각이 들더라고.,현재 상황에서 변화를 주기 위해 어떻게 하면 될까요?,약을 잘 챙겨 먹고 나을 수 있도록 노력해야지.,약을 잘 챙겨 먹어 건강해지시길 바랄게요.,NaN,NaN
2,50882,청소년,여성,학업 및 진로,해당없음,당황,당황,고등학교에 올라오니 중학교 때보다 수업이 갑자기 어려워져서 당황스러워.,고등학교 수업이 중학교 때와는 다르게 갑자기 어려워서 당황스러우시군요.,아직 학기 초인데 내가 수업에 잘 따라갈 수 있을지 걱정돼.,이 상황에서 할 수 있는 게 어떤 것이 있을까요?,중학교 수업을 들을 때보다 훨씬 더 열심히 할 거야.,수업을 어떤 방식으로 열심히 듣는게 좋을까요?,선생님이 강조하신 부분을 필기하고 집에서 매일 수업 내용을 복습하려고 해.,열심히 해서 좋은 결과가 있었으면 좋겠어요.
3,31303,노년,남성,재정,만성질환 무,기쁨,신이 난,재취업이 돼서 받게 된 첫 월급으로 온 가족이 외식을 할 예정이야. 너무 행복해.,재취업 후 첫 월급이라 정말 기쁘시겠어요.,퇴직 후 다시는 돈을 못 벌 줄 알았는데 이렇게 월급으로 가족에게 맛있는 밥을 살 ...,이 기분을 유지하려면 어떻게 해야 할까요?,회사생활을 열심히 해서 계속 월급을 받을거야!,계속 원하시는 대로 회사생활이 이어지길 바랄게요.,NaN,NaN
4,47200,노년,여성,재정,만성질환 유,기쁨,안도,빚을 드디어 다 갚게 되어서 이제야 안도감이 들어.,기분 좋으시겠어요. 앞으로는 어떻게 하실 생각이신가요?,빚도 다 갚았으니 당분간은 아무 생각도 안 하며 살고 싶어.,빚도 다 갚았으니 당분간은 아무 생각도 안 하며 살고 싶으시군요.,NaN,NaN,NaN,NaN

In [66]:
df_feeling.tail()

,번호,연령,성별,상황키워드,신체질환,감정_대분류,감정_소분류,사람문장1,시스템응답1,사람문장2,시스템응답2,사람문장3,시스템응답3,사람문장4,시스템응답4
40874,50789,청년,남성,대인관계,해당없음,불안,혼란스러운,같이 사는 친구가 애완견을 데려왔는데 대부분 내가 돌보고 있어. 내가 주인인가 혼란...,친구 애완견을 대부분 혼자 돌보시는군요. 떠넘겨질까 봐 불안하시겠어요.,나한테 아예 떠넘길 거 같은데 친구한테 얘기해볼까 고민 중이야.,친구분의 생각이 궁금해 얘기해보려고 하시는군요.,이대로 내가 키우게 되면 안 되니까 확실하게 해야겠어.,그렇게 하셨을 떄 지금의 상황이 어떻게 되기를 바라시나요?,친구가 자기가 데려온 강아지에 대해 책임감을 갖고 스스로 잘 돌봤으면 좋겠어.,친구에게 얘기해서 혼자 부담을 떠안지 않으면 좋겠어요.
40875,48959,중년,남성,건강,해당없음,기쁨,안도,지난주에 건강검진 결과가 나왔는데 정상이라고 결과가 나왔어.,검진 결과가 좋게 나와서 안도하겠네요.,결과가 좋게 나와서 다행이야,건강검진에서 좋은결과를 받으신 상황이군요.,NaN,NaN,NaN,NaN
40876,36344,청소년,여성,가족관계,해당없음,슬픔,우울한,엄마는 내 꿈인 작가를 응원해 주고는 했는데 지금은 안 그래. 너무 슬퍼.,어머니의 응원이 사라져서 슬프시겠어요. 조금 더 자세히 말해주시겠어요?,내 재능이 남들보다 월등한 거는 아니라면서 취업해서 안정적으로 살았으면 좋겠다고 하셔.,이 상황에서 무엇을 시도해 보고 싶나요?,내가 다시 내 꿈을 어떻게 이룰 것인지 자세히 설명해 드려야겠어.,꿈을 어떻게 이룰 것인지 엄마에게 이야기해보려 하시는군요.,NaN,NaN
40877,14197,노년,여성,재정,만성질환 무,기쁨,감사하는,이렇게 좋은 운동 시설에서 경로 우대로 운동할 수 있다니 참 행운이야.,운동 시설을 쓸 수 있어서 기분이 좋으시겠어요.,덕분에 건강도 챙길 수 있고 너무 좋아. 안마기도 있던데 내일은 운동하고 안마기도 ...,운동할 때 안마기를 사용하면 어떻게 도움이 되나요?,운동으로 뭉친 근육을 풀어주는 것 같아. 그럼 덜 피로하겠지.,안마기로 피로가 많이 풀리시길 바라요.,NaN,NaN
40878,16248,청년,남성,대인관계,해당없음,불안,스트레스 받는,친구 관계가 너무 힘들어. 베푸는 만큼 돌아오지 않는 것 같아.,많이 서운하셨겠어요. 친구들에게 서운함을 느꼈을 때 해결하는 방법이 있나요?,카페에 가서 대화하거나 같이 술 마시면서 이야기했던 것 같아.,대화로 문제를 해결해오셨던 거군요? 그렇다면 이번 일에는 어떻게 하실 예정인가요?,직접 서운한 감정을 친구에게 얘기하려고 해.,이번에도 대화를 통해 불편한 마음을 풀려고 하시는군요.,NaN,NaN

In [67]:
df_feeling.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40879 entries, 0 to 40878
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   번호      40879 non-null  int64
 1   연령      40879 non-null  object
 2   성별      40879 non-null  object
 3   상황키워드   40879 non-null  object
 4   신체질환    40879 non-null  object
 5   감정_대분류  40879 non-null  object
 6   감정_소분류  40879 non-null  object
 7   사람문장1   40879 non-null  object
 8   시스템응답1  40879 non-null  object
 9   사람문장2   40879 non-null  object
 10  시스템응답2  40879 non-null  object
 11  사람문장3   31059 non-null  object
 12  시스템응답3  31059 non-null  object
 13  사람문장4   1472 non-null   object
 14  시스템응답4  1362 non-null   object
dtypes: int64(1), object(14)
memory usage: 4.7+ MB

In [90]:
data_sns_path = os.path.join("./datasets/korean_sns/Training", "relation.json")

df_sns = pd.read_json(data_sns_path, orient='split')

MemoryError:

아무 생각없이 데이터를 다 불러왔더니 메모리가 누워버렸다.<br>
> 상기 에러와 관계없이 이 데이터만 유독 데이터가 예쁘게 안읽어와진다. script 형식의 데이터가 그대로 담겨지고 column 정보를 읽어오지 못한다. seperator 인자로 해결 가능한 줄 알았는데 불충분한 것인지... 이것도 내일 다시 해보자.

In [ ]:
df_sns.head()

In [ ]:
df_sns.tail()

In [ ]:
df_sns.info()